# Generated by Django 4.1.5 on 2023-02-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('nota', models.TextField(blank=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('isPayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSell', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_menuitem', to='projects.menuitems')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.orders')),
            ],
        ),
    ]
