# Generated by Django 4.1.5 on 2023-02-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('PM', 'Pago movil'), ('EF', 'Efectivo')], max_length=35),
        ),
    ]
