# Generated by Django 4.1.5 on 2023-02-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_orders_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('PM', 'Pago movil'), ('EF', 'Efectivo')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='projects.orders'),
        ),
    ]
